---
version: '3'
services:
  tweets-kafka:
    image: jeqo/apache-kafka:0.11.0.0-2.11
    environment:
      - ZOOKEEPER_CONNECT=tweets-zookeeper:2181
  tweets-zookeeper:
    image: jeqo/apache-kafka-zookeeper:0.11.0.0-2.11
  tweets-worker:
    build: tweets-service-ver2/worker
    ports:
      - 8080
      - 8081
  tweets-indexer:
    build: tweets-service-ver2/indexer
    ports:
      - 8080
      - 8081
  tweets-search:
    build: tweets-service-ver2/search
    ports:
      - 28080:8080
      - 28081:8081
  tweets-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    environment:
          - discovery.type=single-node
          - xpack.security.enabled=false
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
