/*
 * This file is generated by jOOQ.
*/
package io.github.jeqo.demo.infra.jooq;


import io.github.jeqo.demo.infra.jooq.tables.Hashtags;
import io.github.jeqo.demo.infra.jooq.tables.Tweets;
import io.github.jeqo.demo.infra.jooq.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 618835460;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.hashtags</code>.
     */
    public final Hashtags HASHTAGS = io.github.jeqo.demo.infra.jooq.tables.Hashtags.HASHTAGS;

    /**
     * The table <code>public.tweets</code>.
     */
    public final Tweets TWEETS = io.github.jeqo.demo.infra.jooq.tables.Tweets.TWEETS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = io.github.jeqo.demo.infra.jooq.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Hashtags.HASHTAGS,
            Tweets.TWEETS,
            Users.USERS);
    }
}
