/*
 * This file is generated by jOOQ.
*/
package io.github.jeqo.demo.infra.jooq;


import io.github.jeqo.demo.infra.jooq.tables.Hashtags;
import io.github.jeqo.demo.infra.jooq.tables.Tweets;
import io.github.jeqo.demo.infra.jooq.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.hashtags</code>.
     */
    public static final Hashtags HASHTAGS = io.github.jeqo.demo.infra.jooq.tables.Hashtags.HASHTAGS;

    /**
     * The table <code>public.tweets</code>.
     */
    public static final Tweets TWEETS = io.github.jeqo.demo.infra.jooq.tables.Tweets.TWEETS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = io.github.jeqo.demo.infra.jooq.tables.Users.USERS;
}
